---
- name: Install Telegraf
  hosts: localhost
#  connection: local
#  sudo: yes
  become: yes
  roles:
    - telegraf
  vars:
    database: "test2"

- name: influxdb installation
  hosts: localhost
  roles: 
    - influxdb

- name: Install Grafana
  hosts: localhost
  roles: 
    - grafana 
   
