{
 "title": "ECS Cluster",
 "description": "ECS Cluster Usage",
 "tags": [
  "Docker",
  "ECS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ECSCluster",
    "query": "dimension_values(default,AWS/ECS,CPUUtilization,ClusterName)"
   },
   { "name": "datasource" }
  ]
 },
 "panels": [
  { "type": "digiapulssi-breadcrumb-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Average",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    },
    {
     "alias": "Maximum",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Minimum",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Average",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    },
    {
     "alias": "Maximum",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Minimum",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "Memory Reservation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Average",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "MemoryReservation",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    },
    {
     "alias": "Maximum",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "MemoryReservation",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Minimum",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "MemoryReservation",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Minimum" ]
    }
   ]
  },
  {
   "title": "CPU Reservation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Average",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "CPUReservation",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    },
    {
     "alias": "Maximum",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "CPUReservation",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Minimum",
     "dimensions": { "ClusterName": "$ECSCluster" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "CPUReservation",
     "namespace": "AWS/ECS",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Minimum" ]
    }
   ]
  }
 ]
}