{
 "title": "Elasticsearch",
 "description": "Monitoring of Elasticsearch",
 "tags": [ "Elasticsearch" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  { "type": "digiapulssi-breadcrumb-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "ClientId": "987999136054", "DomainName": "sky-ott-test-elastic" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "SampleCount" ]
    }
   ]
  },
  {
   "title": "Searchable Documents",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "987999136054", "DomainName": "sky-ott-test-elastic" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "SearchableDocuments",
     "namespace": "AWS/ES",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Average",
     "dimensions": { "ClientId": "987999136054", "DomainName": "sky-ott-test-elastic" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/ES",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "Average",
     "dimensions": { "ClientId": "987999136054", "DomainName": "sky-ott-test-elastic" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/ES",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "JVM Memory Pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "987999136054", "DomainName": "sky-ott-test-elastic" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "JVMMemoryPressure",
     "namespace": "AWS/ES",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "987999136054", "DomainName": "sky-ott-test-elastic" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "WriteThroughput",
     "namespace": "AWS/ES",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClientId": "987999136054", "DomainName": "sky-ott-test-elastic" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "Nodes",
     "namespace": "AWS/ES",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}