{
 "title": "Google Analytics Dashboard",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  { "type": "digiapulssi-breadcrumb-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Stats Comparison",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Users",
     "groupBy": [
      { "params": [ "tagKey" ], "type": "tag" }
     ],
     "measurement": "ga_user_chart",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "TotalUsers" }
     ]
    },
    {
     "alias": "Returning Users",
     "groupBy": [
      { "params": [ "tagKey" ], "type": "tag" }
     ],
     "measurement": "ga_user_chart",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "ReturningUsers" }
     ]
    },
    {
     "alias": "New Users",
     "groupBy": [
      { "params": [ "tagKey" ], "type": "tag" }
     ],
     "measurement": "ga_user_chart",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "NewUsers" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ga_user_chart",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "TotalUsers" }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ga_user_int",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "SessionCount" }
     ]
    }
   ]
  },
  {
   "title": "Screen Views",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ga_user_int",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "ScreenViews" }
     ]
    }
   ]
  },
  {
   "title": "Returning Users Vs New Users",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Returning Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ga_user_chart",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Returning_Users" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "ReturningUsers" }
     ]
    },
    {
     "alias": "New Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ga_user_chart",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "New_Users" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "NewUsers" }
     ]
    }
   ]
  },
  {
   "title": "Screens / Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ga_user_divide",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "ScreensPerSession" }
     ]
    }
   ]
  },
  {
   "title": "Average Session Duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ga_user_float",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "AverageSessionDuration" }
     ]
    }
   ]
  },
  {
   "title": "Percent New Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "ga_user_float",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tagKey", "operator": "=", "value": "PercentNewSessions" }
     ]
    }
   ]
  },
  {
   "title": "Request Regions",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "country" ], "type": "tag" }
     ],
     "measurement": "worldmap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}