{
 "title": "Customer Service",
 "description": "Visualize metrics of applications",
 "tags": [
  "app",
  "docker",
  "elb",
  "alb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "aws_datasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  { "type": "digiapulssi-breadcrumb-panel", "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 } },
  {
   "title": "Application Exception Count",
   "type": "singlestat",
   "description": "Click here to go to real time log dashboard.",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "exception",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Error Count",
   "type": "singlestat",
   "description": "Click here to go to real time log dashboard.",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "error",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NewRelic Detailed Monitoring",
   "type": "text",
   "description": "Click here to go to the application Newrelic dashboard.",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 0 },
   "content": "<div style=\"cursor: pointer;\" onclick=\"window.open('https://rpm.newrelic.com/accounts/2115264/applications/198595151','_blank')\">\n   <h3><center>NewRelic Detailed Monitoring</center></h3>\n</div>"
  },
  {
   "title": "Real Time Logs",
   "type": "text",
   "description": "Click here to go to the Real Time log trail.",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 1 },
   "content": "<div style=\"cursor: pointer;\" onclick=\"window.open('http://tabcorp-test-kibana.tothenew.net/app/logtrail#/?q=*&h=test-customer-service&t=Now&i=test-*&_g=()','_blank')\">\n   <h3><center>Real Time Logs</center></h3>\n</div>"
  },
  {
   "title": "Elastic APM",
   "type": "text",
   "description": "Click here to go to the Elastic APM Monitoring",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 2 },
   "content": "<div style=\"cursor: pointer;\" onclick=\"window.open('http://tabcorp-test-kibana.tothenew.net/app/kibana#/dashboard/41b5d920-7821-11e7-8c47-65b845b5cfb3?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-30m,mode:quick,to:now))&_a=(description:'',filters:!(),fullScreenMode:!f,options:(darkTheme:!f,useMargins:!f),panels:!((embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:10,i:'1',w:12,x:0,y:3),id:a2e199b0-7820-11e7-8c47-65b845b5cfb3,panelIndex:'1',type:visualization,version:'6.2.2'),(gridData:(h:3,i:'2',w:6,x:0,y:0),id:'09bcf890-7822-11e7-8c47-65b845b5cfb3',panelIndex:'2',type:visualization,version:'6.2.2'),(gridData:(h:3,i:'3',w:6,x:6,y:0),id:'55606a60-7823-11e7-8c47-65b845b5cfb3',panelIndex:'3',type:visualization,version:'6.2.2')),query:(language:lucene,query:''),timeRestore:!f,title:'%5BAPM%5D%20Transactions',viewMode:view)','_blank')\">\n   <h3><center>Elastic APM</center></h3>\n</div>"
  },
  { "title": "Frontend Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Transaction Time [APM]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms", "label": "Transaction Time [APM]" }
   ],
   "targets": [
    {
     "alias": "Time",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "transaction.duration.us",
       "id": "1",
       "inlineScript": "_value/1000",
       "meta": {},
       "settings": { "script": { "inline": "_value/1000" } },
       "type": "avg"
      }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Transaction Per Minute [APM]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "transaction.duration.us",
       "id": "1",
       "inlineScript": "_value/1000",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Transaction Response Times [APM]",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "transaction.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metrics": [
      {
       "field": "transaction.duration.us",
       "id": "1",
       "inlineScript": "_value/1000",
       "meta": {},
       "settings": { "script": { "inline": "_value/1000" } },
       "type": "avg"
      }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "http_response",
     "region": "default",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "appname", "operator": "=", "value": "customer-service" }
     ]
    }
   ]
  },
  {
   "title": "Healthy Hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Current Request Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "measurement": "http_response",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "statistics": [ "SampleCount" ],
     "tags": [
      {
       "key": "server",
       "operator": "=",
       "value": "https://tabcorp-test.tothenew.net/homescreen-service/actuators/info/"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Target Response Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Target Response Time",
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "300",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "LB To EC2 Response Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Unhealthy Host Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "measurement": "http_response",
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      {
       "key": "server",
       "operator": "=",
       "value": "https://tabcorp-test.tothenew.net/homescreen-service/actuators/info/"
      }
     ]
    }
   ]
  },
  {
   "title": "Target Connection Error Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "TargetConnectionErrorCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "SampleCount" ]
    }
   ]
  },
  {
   "title": "API Flow",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 17 },
   "format": "s",
   "valueName": "avg",
   "content": "graph LR\nA[fa:fa-user-circle https://tabcorp-test.tothenew.net/customer-service] .->C{KONG-API-Gateway}\nC -.customer-service.->  E(fa:fa-server customer-service Docker Container)\nE-.MySQL Aurora.->I(fa:fa-database MySQL Aurora DB)\nE-.RabbitMQ.->J(fa:fa-server RabbitMQ Cluster)\nE-.MongoDB.-> K(fa:fa-database MongoDB Cluster)",
   "targets": [
    {
     "alias": "A",
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "appname", "operator": "=", "value": "customer-service" }
     ]
    },
    {
     "alias": "E",
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "appname", "operator": "=", "value": "customer-service" }
     ]
    },
    {
     "alias": "J",
     "measurement": "net_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "rabbit1.test.skyott.in.cld" }
     ]
    },
    {
     "alias": "I",
     "measurement": "net_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "server",
       "operator": "=",
       "value": "mysql-db-cluster.test.skyott.in.cld"
      }
     ]
    },
    {
     "alias": "K",
     "measurement": "net_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "mongodb1.test.skyott.in.cld" }
     ]
    },
    {
     "alias": "C",
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-alb/69898112f279ff12",
      "TargetGroup": "targetgroup/kong-test/93168ff9e325ff81"
     },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "ap-southeast-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "300",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "300",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": {
      "LoadBalancer": "app/sky-ott-test-internal-alb/8fbb2536fee887bd",
      "TargetGroup": "targetgroup/customer-service-test/7f195ad7d82bb798"
     },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "300",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "Application Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Avg. Mem. Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "sky-ott-test-cluster", "ServiceName": "customer-service-test-service" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "ap-southeast-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Avg. Mem. Reservation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "sky-ott-test-cluster" },
     "metricName": "MemoryReservation",
     "namespace": "AWS/ECS",
     "region": "ap-southeast-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Avg. Cpu Reservation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "sky-ott-test-cluster" },
     "metricName": "CPUReservation",
     "namespace": "AWS/ECS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Avg.CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "sky-ott-test-cluster", "ServiceName": "customer-service-test-service" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Average Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "ClusterName": "sky-ott-test-cluster", "ServiceName": "customer-service-test-service" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": { "ClusterName": "sky-ott-test-cluster", "ServiceName": "customer-service-test-service" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Backend Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "MySQL Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "sky-ott-test-aurora" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MySQL Replication Lag",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 37 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "sky-ott-test-aurora-aurora-replica"
     },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "metricName": "AuroraReplicaLag",
     "namespace": "AWS/RDS",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Current Rabbit Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "sky-ott-test-aurora" },
     "measurement": "rabbitmq_overview",
     "metricName": "AuroraReplicaLag",
     "namespace": "AWS/RDS",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "connections" ], "type": "field" }
      ]
     ],
     "statistics": [ "SampleCount" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test-rabbit1" }
     ]
    }
   ]
  },
  {
   "title": "Current Rabbit Consumers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "sky-ott-test-aurora" },
     "measurement": "rabbitmq_overview",
     "metricName": "AuroraReplicaLag",
     "namespace": "AWS/RDS",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" }
      ]
     ],
     "statistics": [ "SampleCount" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test-rabbit1" }
     ]
    }
   ]
  },
  {
   "title": "CPUUtilization-MySQL",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Utilization Master",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "sky-ott-test-aurora" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    },
    {
     "alias": "CPU Utilization Replica",
     "application": { "filter": "" },
     "dimensions": {
      "DBInstanceIdentifier": "sky-ott-test-aurora-aurora-replica"
     },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Free-Memory-MySQL",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Free Utilization Master",
     "application": { "filter": "" },
     "dimensions": { "DBInstanceIdentifier": "sky-ott-test-aurora" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    },
    {
     "alias": "Free Utilization Replica",
     "application": { "filter": "" },
     "dimensions": {
      "DBInstanceIdentifier": "sky-ott-test-aurora-aurora-replica"
     },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "options": {
      "showDisabledItems": false
     },
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU & Memory Usage-Rabbit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU-Rabbit1",
     "measurement": "cpu",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test-rabbit1" }
     ]
    },
    {
     "alias": "CPU-Rabbit2",
     "measurement": "cpu",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test-rabbit2" }
     ]
    },
    {
     "alias": "CPU-Rabbit3",
     "measurement": "cpu",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test-rabbit3" }
     ]
    },
    {
     "alias": "Mem-Rabbit3",
     "measurement": "mem",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test-rabbit3" }
     ]
    },
    {
     "alias": "Mem-Rabbit2",
     "measurement": "mem",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test-rabbit2" }
     ]
    },
    {
     "alias": "Mem-Rabbit1",
     "measurement": "mem",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test-rabbit1" }
     ]
    }
   ]
  },
  {
   "title": "CPU & Memory Usage-Mongo",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU-node1",
     "measurement": "cpu",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mongodb1.test.skyott.in.cld" }
     ]
    },
    {
     "alias": "CPU-Node2",
     "measurement": "cpu",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mongodb2.test.skyott.in.cld" }
     ]
    },
    {
     "alias": "CPU-Node3",
     "measurement": "cpu",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mongodb3.test.skyott.in.cld" }
     ]
    },
    {
     "alias": "Mem-Node1",
     "measurement": "mem",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mongodb1.test.skyott.in.cld" }
     ]
    },
    {
     "alias": "Mem-Node2",
     "measurement": "mem",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mongodb2.test.skyott.in.cld" }
     ]
    },
    {
     "alias": "Mem-Node2",
     "measurement": "mem",
     "region": "ap-southeast-2",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "host", "operator": "=", "value": "mongodb3.test.skyott.in.cld" }
     ]
    }
   ]
  }
 ]
}