{
 "title": "RabbitMQ",
 "description": "RabbitMQ Dashboard",
 "tags": [ "Rabbitmq" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   { "name": "datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  { "type": "digiapulssi-breadcrumb-panel", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Logs",
   "type": "singlestat",
   "description": "Click here to view logs",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Consumers",
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"consumers\"), 1m) AS consumers FROM rabbitmq_overview WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"connections\"), 1m) AS connections FROM rabbitmq_overview WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "connections" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"queues\"), 1m) AS messages FROM rabbitmq_overview WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "queues" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages Delievered",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"messages_delivered\"), 1m) AS messages_delievered FROM rabbitmq_overview WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "messages_delivered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Clustering Listeners",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"consumers\"), 1m) AS consumers FROM rabbitmq_overview WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "clustering_listeners" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages Published",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"messages_publish_in\"), 1m) AS messages FROM rabbitmq_exchange WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "messages_published" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"channels\"), 1m) AS messages FROM rabbitmq_overview WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "channels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "AMQP Listeners",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"messages_publish_out\"), 1m) AS messages_published_out FROM rabbitmq_exchange WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "amqp_listeners" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"channels\"), 1m) AS messages FROM rabbitmq_overview WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "messages_ready" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "rabbitmq_overview",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"messages_publish_in\"), 1m) AS messages FROM rabbitmq_exchange WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "exchanges" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SKY_OTT_INSERT_COMPOSITE Queue Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Messages Published",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_queue",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"messages_publish_in\"), 1m) AS messages FROM rabbitmq_exchange WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "messages" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "ott_insert_composite" }
     ]
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_queue",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"messages_publish_in\"), 1m) AS messages FROM rabbitmq_exchange WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "ott_insert_composite" }
     ]
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "Count" }
   ],
   "targets": [
    {
     "measurement": "rabbitmq_queue",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"messages_publish_in\"), 1m) AS messages FROM rabbitmq_exchange WHERE time > now() - 10m GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "ott_insert_composite" }
     ]
    }
   ]
  },
  {
   "title": "Idle Since",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "idle_since" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "ott_insert_composite" }
     ]
    }
   ]
  },
  {
   "title": "Messages Publish",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_publish" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "queue", "operator": "=", "value": "ott_insert_composite" }
     ]
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Disk",
     "measurement": "disk",
     "query": "SELECT mean(\"TotalAlloc\")/1024 FROM \"runtime\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory",
     "measurement": "mem",
     "query": "SELECT mean(\"TotalAlloc\")/1024 FROM \"runtime\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       { "params": [ "load 1m" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       { "params": [ "load 5m" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       { "params": [ "load 15m" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}